beranda/urls.py
from django.urls import path
from . import views

app_name = 'beranda'

urlpatterns = [
    path('', views.beranda, name='beranda'),
    path('tentang/', views.tentang, name='tentang'),
	path('proyek/', views.proyek, name='proyek'),
    # dilanjutkan ...
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('beranda.urls')),
]

beranda/models.py
from django.db import models

# Create your models here.

beranda/views.py
from django.shortcuts import render

# Create your views here.
def beranda(request):
	return render(request, 'beranda.html')

def tentang(request):
	return render(request, 'tentang.html')	

def proyek(request):
	return render(request, 'proyek.html')

beranda/templates/beranda.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Faza Ghani Irham</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'image/f..png' %}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bootstrap.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet"> 
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container-fluid" style="max-height:13.889vw;min-height:5.556vw; max-width:120%; margin-bottom: 1vw;">
    <nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
        <a class="navbar-brand mb-0" style="margin-right: 0px;margin-left: 1.389vw;" href="#">
          <img class = "itu" src="{% static 'image/weblogo.png' %}">
        </a>
        <button class="navbar-toggler apa justify-content-end" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="nav nav-pills justify-content-end ini" style="margin-right: 1.389vw;">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'beranda:beranda' %}">Beranda</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'beranda:tentang' %}">Tentang</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'beranda:proyek' %}">Proyek</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#kontak">Kontak</a>
          </li>
        </ul>
      </div>
      </nav>
    </div>
  <div class="container container-gambar" style="max-width: 120%; background-image: url('/static/image/fotoweb1.png'); background-size: 120%; background-repeat: no-repeat;">
        <div class="col-lg-12 text-center">
            <div class="h1" style="color:#fff;">Halo, Saya Irham</div>
        </div>
    </div>
    <div class="container" style="height: 48.6vw;max-width: 120%;">
      <div class="col-lg-12 text-center">
         <h1 class="atas" style="padding-top: 7vw; ">
          Tentang Saya
         </h1>
        <p class="d-flex justify-content-around text-justify" style="margin-top:5.5vw; padding-left: 10%;padding-right: 10%; margin-bottom:5.5vw;">
          Mahasiswa Semester 3 Jurusan Sistem Informasi Universitas 
          Indonesia. Tertarik kepada UI/UX design dan data science. 
          Bermain futsal menjadi kiper di waktu luang sebagai hobi. 
          Lulusan pesantren yang sekarang menimba ilmu di dunia IT.
        </p>
        <a class="selebihnya" style="padding-top:7vw;margin-bottom:1.4vw;" href="{% url 'beranda:tentang' %}">
          > Selengkapnya tentang saya
        </a>
      </div>
    </div>
    <div class="container" style="height: 48.6vw;max-width: 120%; margin-bottom:7vw;">
      <div class="col-lg-12 text-center">
         <h1 class="atas" style="padding-top: 7vw; ">
          Proyek
         </h1>
         <div class="d-flex justify-content-around" style="margin-top: 5.5vw; margin-bottom:7vw;">
          <div class="p-2 bd-highlight"><img class="img-fluid" src="{% static 'image/techmeet.png' %}"></div>
          <div class="p-2 bd-highlight"><img class="img-fluid" src="{% static 'image/17an.png' %}"></div>
          <div class="p-2 bd-highlight"><img class="img-fluid" src="{% static 'image/runtime.png' %}"></div>
          <div class="p-2 bd-highlight"><img class="img-fluid" src="{% static 'image/hotline.png' %}"></div>
        </div>
        <a class="selebihnya" style="padding-top:7vw;margin-bottom:1.4vw;" href="{% url 'beranda:proyek' %}">
          > Lihat lebih banyak proyek saya
        </a>
      </div>
    </div>
    <div class="container text-right" style="height: 45vw;max-width: 120%; background-color: black;" id="kontak">
         <h1 class="atas" style="padding-top:9vw;margin-bottom:2.8vw;margin-right:5.5vw;color:#ffffff;">
          Tetap Terhubung
         </h1>
         <p style="color: #ffffff;margin-top:6vw;margin-bottom: 8.3vw;margin-right:5.5vw">
          Ikuti saya dan dapatkan info terbaru tentang saya
        </p>
        <div class="d-flex justify-content-around" style="margin-top: 4.2vw; margin-left: 42vw; margin-right:2vw;">
          <a class="gambar p-2 bd-highlight" href="https://www.instagram.com/fgirham/" target="_blank"><img class="img-fluid" style="width:4vw;" src="{% static 'image/ig.png' %}"></a>
          <a class="gambar p-2 bd-highlight" href="https://www.facebook.com/fghaniirham1" target="_blank"><img class="img-fluid" style="width:4vw;"src="{% static 'image/fb.png' %}"></a>
          <a class="gambar p-2 bd-highlight" href="https://twitter.com/fgirham/" target="_blank"><img class="img-fluid" style="width:4vw;"src="{% static 'image/tw.png' %}"></a>
          <a class="gambar p-2 bd-highlight" href="https://www.linkedin.com/in/faza-ghani-i-b98170136/" target="_blank"><img class="img-fluid"style="width:4vw;" src="{% static 'image/in.png' %}"></a>
        </div>
    </div>  
</body>
</html>

beranda/templates/proyek.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Faza Ghani Irham</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'image/f..png' %}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bootstrap.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet"> 
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container-fluid" style="max-height:200px;min-height: 100px; max-width:120%;">
    <nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
        <a class="navbar-brand mb-0 h1" style="margin-left: 20px;" href="#">
          <img class = "itu" src="{% static 'image/weblogo.png' %}">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="nav nav-pills justify-content-end ini" style="margin-right: 1.389vw;">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'beranda:beranda' %}">Beranda</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'beranda:tentang' %}">Tentang</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'beranda:proyek' %}">Proyek</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#kontak">Kontak</a>
          </li>
        </ul>
      </div>
      </nav>
    </div>
    <div class="container" style="max-width:120%; padding-right: 4.861vw ;padding-left: 4.861vw ;">
        <h1 id="palingatas" class="atas text-left" style="margin-top:5vw;margin-left:5vw;color:#000000;">
            Beberapa yang sudah saya buat
        </h1>
        <div class="d-flex justify-content-around" style="margin-top: 7vw; margin-bottom:5vw;">
          <div class="p-2 bd-highlight"><img class="img-fluid" src="{% static 'image/runtime.png' %}"></div>
          <div class="p-2 bd-highlight"><img class="img-fluid" src="{% static 'image/runtime2.png' %}"></div>
          <div class="p-2 bd-highlight"><img class="img-fluid" src="{% static 'image/kaus.png' %}"></div>
          <div class="p-2 bd-highlight"><img class="img-fluid" src="{% static 'image/kaus2.png' %}"></div>
        </div>
        <div class="d-flex justify-content-around" style="margin-top: 5vw; margin-bottom:5vw;">
          <div class="p-2 bd-highlight"><img class="img-fluid" src="{% static 'image/techmeet.png' %}"></div>
          <div class="p-2 bd-highlight"><img class="img-fluid" src="{% static 'image/17an.png' %}"></div>
          <div class="p-2 bd-highlight"><img class="img-fluid" src="{% static 'image/hotline.png' %}"></div>
          <div class="p-2 bd-highlight"><img class="img-fluid" src="{% static 'image/runtime3.png' %}"></div>
        </div>
        <div class="d-flex justify-content-around" style="margin-top: 5vw; margin-bottom:13vw;">
          <div class="p-2 bd-highlight"><img class="img-fluid" src="{% static 'image/compfest.png' %}"></div>
          <div class="p-2 bd-highlight"><img class="img-fluid" src="{% static 'image/pmb.png' %}"></div>
          <div class="p-2 bd-highlight"><img class="img-fluid" src="{% static 'image/medpar.png' %}"></div>
          <div class="p-2 bd-highlight"><img class="img-fluid" src="{% static 'image/pmb2.png' %}"></div>
        </div>
      </div>
    <div class="container text-right" style="height: 45vw;max-width: 120%; background-color: black;" id="kontak">
         <h1 class="atas" style="padding-top:9vw;margin-bottom:2.8vw;margin-right:5.5vw;color:#ffffff;">
          Tetap Terhubung
         </h1>
         <p style="color: #ffffff;margin-top:6vw;margin-bottom: 8.3vw;margin-right:5.5vw">
          Ikuti saya dan dapatkan info terbaru tentang saya
        </p>
        <div class="d-flex justify-content-around" style="margin-top: 4.2vw; margin-left: 42vw; margin-right:2vw;">
          <a class="gambar p-2 bd-highlight" href="https://www.instagram.com/fgirham/" target="_blank"><img class="img-fluid" style="width:4vw;" src="{% static 'image/ig.png' %}"></a>
          <a class="gambar p-2 bd-highlight" href="https://www.facebook.com/fghaniirham1" target="_blank"><img class="img-fluid" style="width:4vw;"src="{% static 'image/fb.png' %}"></a>
          <a class="gambar p-2 bd-highlight" href="https://twitter.com/fgirham/" target="_blank"><img class="img-fluid" style="width:4vw;"src="{% static 'image/tw.png' %}"></a>
          <a class="gambar p-2 bd-highlight" href="https://www.linkedin.com/in/faza-ghani-i-b98170136/" target="_blank"><img class="img-fluid"style="width:4vw;" src="{% static 'image/in.png' %}"></a>
        </div>
    </div>  
</body>
</html>

beranda/templates/tentang.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Faza Ghani Irham</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'image/f..png' %}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bootstrap.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet"> 
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container-fluid" style="max-height:200px;min-height: 100px; max-width:120%;">
    <nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
        <a class="navbar-brand mb-0 h1" style="margin-left: 20px;" href="#">
          <img class = "itu" src="{% static 'image/weblogo.png' %}">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="nav nav-pills justify-content-end ini" style="margin-right: 1.389vw;">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'beranda:beranda' %}">Beranda</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'beranda:tentang' %}">Tentang</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'beranda:proyek' %}">Proyek</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#kontak">Kontak</a>
          </li>
        </ul>
      </div>
      </nav>
    </div>
    <div class="container" style="height:63.3vw;max-width: 120%; background-image: url('/static/image/foto.jpg'); background-repeat: no-repeat; background-size: 48%">
        <h1 id="palingatas" class="atas" style="padding-top:4vw;margin-left:48.611vw;margin-right:6.944vw;color:#000000;">
            Halo, Saya Irham. Mahasiswa, Desainer, Programmer, Kiper.
        </h1>
        <p class="d-flex justify-content-around" style="margin-top:4vw;margin-left:48.611vw;margin-right:6.944vw;color:#000000;">
                Mahasiswa Semester 3 Jurusan Sistem Informasi Universitas 
                Indonesia. Tertarik kepada UI/UX design dan data science. 
                Bermain futsal menjadi kiper di waktu luang sebagai hobi. 
                Lulusan pesantren yang sekarang menimba ilmu di dunia IT.
              </p>
    </div>
    <div class="container" style="height:63.3vw; max-width: 120%;background-color: #EDEDED;">
        <h1 class="atas text-left" style="color:#000000;padding-top: 6vw;margin-left: 7vw; margin-right: 30vw;">
            Saya, Sepak Bola, Pesantren, dan Desain Visual
        </h1>
        <div class="col-lg-12 text-center">
        <p style="margin-top:5vw;margin-left: 4vw;margin-right: 4vw;column-count: 2; column-gap: 5vw; text-align:justify;">
            Lorem ipsum dolor sit amet et delectus accommodare his consul copiosae legendos at vix ad putent delectus delicata 
            usu. Vidit dissentiet eos cu eum an brute copiosae hendrerit. Eos erant dolorum an. Per facer affert ut. Mei iisque 
            mentitum moderatius cu. Sit munere facilis accusam eu dicat falli consulatu at vis. Te facilisis mnesarchum qui posse 
            omnium mediocritatem est cu. Modus argumentum ne qui tation efficiendi in eos. Ei mea falli legere efficiantur et 
            tollit aliquip debitis mei. No deserunt mediocritatem 
        </p>
        </div>
    </div>
    <div class="container" style="padding-top:4vw;max-width: 120%;">
        <h1 class="atas text-left" style="color:#000000;margin-left:7vw;margin-right: 30vw;">
            Kemampuan
        </h1>
        <img class="img-fluid" src="{% static 'image/kemampuan.png' %}" style="width:82.500vw;margin-left:7.639vw;margin-top:7vw;margin-bottom:8vw;">
    </div>
    <div class="container" style="padding-top:4vw;max-width: 120%;">
        <h1 class="atas" style="color:#000000;margin-left:7vw;margin-right: 30vw;">
            Pengalaman Kepanitiaan
        </h1>
        <img class="img-fluid" src="{% static 'image/pengalaman.png' %}" style="width:75.972vw;margin-left:10vw;margin-top:7vw;margin-bottom:8vw;">
</div>
    <div class="container text-right" style="height: 45vw;max-width: 120%; background-color: black;" id="kontak">
         <h1 class="atas" style="padding-top:9vw;margin-bottom:2.8vw;margin-right:5.5vw;color:#ffffff;">
          Tetap Terhubung
         </h1>
         <p style="color: #ffffff;margin-top:6vw;margin-bottom: 8.3vw;margin-right:5.5vw">
          Ikuti saya dan dapatkan info terbaru tentang saya
        </p>
        <div class="d-flex justify-content-around" style="margin-top: 4.2vw; margin-left: 42vw; margin-right:2vw;">
          <a class="gambar p-2 bd-highlight" href="https://www.instagram.com/fgirham/" target="_blank"><img class="img-fluid" style="width:4vw;" src="{% static 'image/ig.png' %}"></a>
          <a class="gambar p-2 bd-highlight" href="https://www.facebook.com/fghaniirham1" target="_blank"><img class="img-fluid" style="width:4vw;"src="{% static 'image/fb.png' %}"></a>
          <a class="gambar p-2 bd-highlight" href="https://twitter.com/fgirham/" target="_blank"><img class="img-fluid" style="width:4vw;"src="{% static 'image/tw.png' %}"></a>
          <a class="gambar p-2 bd-highlight" href="https://www.linkedin.com/in/faza-ghani-i-b98170136/" target="_blank"><img class="img-fluid"style="width:4vw;" src="{% static 'image/in.png' %}"></a>
        </div>
    </div>  
</body>
</html>